# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b1b8489d51db577ce640faa4b00d961678e325d0db6004c209528e658f473320b4c80bf23e3b70dda17e898a3e294711c93287659660ceb46d3031c0ba7b974b

test:
  secret_key_base: 547995a3f3f6fc23b8a6e93edbb666a7e21ca1218d2f4f04aba31711a7707f1a9dda0e47ed302a56155c625ddad7fd9b5ceb84746560306b6005b70ddde09665

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
